version: '3.1'

services:

  db:
    image:  postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: danilo
    volumes:
      - /database:/var/lib/postgresql
    ports:
      - "5432:5432"
