version: '3.1'

services:

  db:
    image:  postgres:alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: danilo
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
